# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.25.0
import dataclasses
from typing import Optional


@dataclasses.dataclass()
class SqlcTest:
    name: str
    description: Optional[str]
